openapi: 3.0.0
info:
  title: Weather Info API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: https://api.weathersinfo.com/v1
    description: Main (production) server
  - url: https://staging-api.weathersinfo.com/v1
    description: Internal staging server for testing
  - url: https://localhost:5001/v1
    description: Local server for development

paths:
  /cities:
    $ref: './cities/getByCityName.yaml'
  /geos:
    $ref: './geos/getByLatLong.yaml'

components:
  schemas:
    WeatherInfo:
      $ref: './shared/weatherinfo.yaml'
